# Generated by Django 3.0.6 on 2020-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0002_auto_20200518_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='year',
            field=models.CharField(default=2020, max_length=10),
        ),
    ]
