# Generated by Django 3.0.6 on 2020-05-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0024_auto_20200522_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='prev_sl_bal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prev_vl_bal',
            field=models.FloatField(default=0.0),
        ),
    ]
