# Generated by Django 3.0.6 on 2020-05-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='name',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='name',
            new_name='employee',
        ),
    ]
