# Generated by Django 3.0.6 on 2020-05-20 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0003_leave_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='month',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='year',
        ),
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 7, 4, 48, 436047, tzinfo=utc)),
        ),
    ]
