# Generated by Django 3.0.6 on 2020-05-22 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0015_auto_20200522_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='time_in',
            field=models.TimeField(default=datetime.time(1, 57, 21, 735959)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time_out',
            field=models.TimeField(default=datetime.time(1, 57, 21, 735959)),
        ),
    ]
