# Generated by Django 3.0.6 on 2020-05-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0029_employee_employee_tin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_tin_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
