# Generated by Django 3.0.6 on 2020-05-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('probation_date', models.DateTimeField()),
                ('hired_date', models.DateTimeField()),
                ('sl_start_date', models.DateTimeField()),
                ('regularization_date', models.DateTimeField()),
                ('employee_status', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('project', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=2)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.Employee')),
            ],
        ),
    ]
