# Generated by Django 3.0.6 on 2020-05-21 02:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0005_auto_20200521_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('R', 'Regular Employee'), ('R1', 'Regular1 Employee'), ('P', 'Probationary Employee')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 2, 19, 32, 296829, tzinfo=utc)),
        ),
    ]
