# Generated by Django 3.0.6 on 2020-05-21 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0006_auto_20200521_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 2, 41, 39, 744952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('VL', 'Vacation Leave'), ('SL', 'Sick Leave')], default='VL', max_length=2),
        ),
    ]
