# Generated by Django 3.0.6 on 2020-05-21 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0007_auto_20200521_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='prev_leave_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 3, 54, 39, 26860, tzinfo=utc)),
        ),
    ]
