# Generated by Django 3.0.6 on 2020-05-21 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0009_auto_20200521_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 4, 8, 34, 52887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 4, 8, 34, 52887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2020, 5, 21, 4, 8, 34, 52887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time_out',
            field=models.TimeField(default=datetime.datetime(2020, 5, 21, 4, 8, 34, 52887, tzinfo=utc)),
        ),
    ]
