# Generated by Django 3.0.6 on 2020-05-22 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0013_auto_20200522_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnedleave',
            name='cut_off',
            field=models.DateField(default=datetime.date(2020, 5, 22)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 1, 52, 22, 819559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='probation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 1, 52, 22, 819559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='regularization_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 1, 52, 22, 819559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 1, 52, 22, 819559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 22)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 22)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time_in',
            field=models.TimeField(default=datetime.time(1, 52, 22, 854616)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time_out',
            field=models.TimeField(default=datetime.time(1, 52, 22, 854616)),
        ),
    ]
