# Generated by Django 3.0.6 on 2020-05-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0017_auto_20200522_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
