# Generated by Django 3.0.6 on 2020-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0018_auto_20200522_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='value',
            new_name='days',
        ),
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
