# Generated by Django 3.0.6 on 2020-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0023_auto_20200522_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnedleave',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='days',
            field=models.FloatField(default=0.0),
        ),
    ]
