# Generated by Django 3.0.6 on 2020-05-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0026_offenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offenses',
            new_name='Offense',
        ),
    ]
