# Generated by Django 3.0.6 on 2020-05-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0030_auto_20200528_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offense',
            name='offense_name',
            field=models.CharField(max_length=20),
        ),
    ]
